# Generated by Django 4.1.3 on 2023-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_projects_event_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='worker',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
