# Generated by Django 4.1.3 on 2023-04-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_projects_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='project_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='projects',
            name='worker',
            field=models.CharField(max_length=150),
        ),
    ]
