# Generated by Django 4.1.3 on 2023-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_alter_event_project_name_alter_projects_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
