# Generated by Django 4.1.3 on 2023-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='TO DO', max_length=50),
        ),
    ]
