# Generated by Django 4.1.3 on 2023-05-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0007_event_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='To Do', max_length=50),
        ),
    ]
